-- -- +migrate Up
-- -- SQL in section 'Up' is executed when this migration is applied
-- CREATE table if not exists "users"
-- (
--     "id"    varchar UNIQUE NOT NULL,
--     "type"  varchar        NOT null,
--     "delta" bigint,
--     "value" decimal,
--     "hash"  varchar
-- );
--
-- -- +migrate Down
-- -- SQL section 'Down' is executed when this migration is rolled back
-- DROP TABLE IF EXISTS "users";
